# requierments.yml file
# https://anaconda.org/conda-forge/chatterbot_corpus

name: test1
channels:
  - defaults
  - https://conda.anaconda.org/conda-forge/
dependencies:
  - jupyter=1.0.0
  - jupyterlab=4.0.11
  - scikit-learn
  - matplotlib
  - numpy
  - pandas
  - ChatterBot==1.0.5
  - chatterbot-corpus==1.2.0
  - click==8.1.7
  - coveralls
  - flake8
  - joblib==1.4.2
  - mathparse>=0.1,<0.2
  - nltk>=3.2,<4.0
  - nose
  - pint>=0.8.1
  - pymongo>=3.3,<4.0
  - python-dateutil>=2.8,<2.9
  - pytz
  - pyyaml>=5.3,<5.4
  - regex==2024.7.24
  - six==1.16.0
  - twine
  - twython
  - spacy>=2.1,<2.2
  - sphinx>=3.0,<3.1
  - sphinx_rtd_theme
  - sqlalchemy>=1.3,<1.4
  - tqdm==4.66.5
  - python